# Homework 4: Pandas

This notebook has two parts. **Part I** introduces the core pandas concepts you'll need, with short exercises to practice each one. **Part II** applies those skills to a real-world dataset of financial crises spanning 70+ countries and two centuries.

Work through Part I first — the exercises are quick and designed to build muscle memory. By the time you reach Part II, the patterns will feel familiar.

---
# Part I: Introduction to Pandas

## 1. What Is a DataFrame?

A DataFrame is essentially a spreadsheet inside Python. It has rows and columns, just like an Excel sheet, but you can manipulate it with code instead of clicking around.

Let's start by importing pandas and building a tiny dataset by hand.

In [1]:
import pandas as pd

# A DataFrame can be created from a dictionary.
# Each key becomes a column name; each value is a list of entries.

data = {
    "country": ["Brazil", "Germany", "Japan", "Nigeria", "United States"],
    "population_millions": [214, 84, 125, 223, 333],
    "gdp_trillions_usd": [1.92, 4.26, 4.23, 0.44, 25.46],
    "region": ["South America", "Europe", "Asia", "Africa", "North America"]
}

df = pd.DataFrame(data)
df

         country  population_millions  gdp_trillions_usd         region
0         Brazil                  214               1.92  South America
1        Germany                   84               4.26         Europe
2          Japan                  125               4.23           Asia
3        Nigeria                  223               0.44         Africa
4  United States                  333              25.46  North America

That's it — five rows, four columns. The numbers on the left (0, 1, 2, ...) are the **index**. Pandas adds this automatically to give every row a label.

Take a moment to notice the structure: each *row* is a country, and each *column* is a variable we know about that country. This "one row per observation, one column per variable" pattern is the foundation of tidy data, and it's how you'll want to organize most datasets.

### Exercise 1

Create a DataFrame called `un_members` with data for four countries of your choice. It should have three columns: `"country"`, `"year_joined_un"`, and `"continent"`. Display the result.

In [2]:
# Your code here
un_members = {
    "country": ['Norway', 'Canada', 'Japan', 'Ghana'],
    "year_joined_un": [1995, 1974, 1985, 1999],
    "continent": ['Europe', 'North America', "Asia", "Africa"]
}

df1 = pd.DataFrame(un_members)
df1

  country  year_joined_un      continent
0  Norway            1995         Europe
1  Canada            1974  North America
2   Japan            1985           Asia
3   Ghana            1999         Africa

---
## 2. Getting Your Bearings: Inspecting a DataFrame

Before you do anything with data, you need to understand what you're looking at. Pandas gives you a handful of methods for this. These are the ones you'll use constantly.

In [3]:
# .shape tells you (rows, columns)
df.shape

(5, 4)

In [4]:
# .columns lists all column names
df.columns

Index(['country', 'population_millions', 'gdp_trillions_usd', 'region'], dtype='object')

In [5]:
# .dtypes shows the data type of each column
# 'object' usually means text/string; 'int64' and 'float64' are numbers
df.dtypes

country                 object
population_millions      int64
gdp_trillions_usd      float64
region                  object
dtype: object

In [6]:
# .head(n) shows the first n rows (default 5)
# .tail(n) shows the last n rows
# These are essential when your dataset has thousands of rows
# and you just want a quick peek.

df.head(3)

   country  population_millions  gdp_trillions_usd         region
0   Brazil                  214               1.92  South America
1  Germany                   84               4.26         Europe
2    Japan                  125               4.23           Asia

In [7]:
# .describe() gives summary statistics for numeric columns
df.describe()

       population_millions  gdp_trillions_usd
count             5.000000           5.000000
mean            195.800000           7.262000
std              96.704188          10.301079
min              84.000000           0.440000
25%             125.000000           1.920000
50%             214.000000           4.230000
75%             223.000000           4.260000
max             333.000000          25.460000

**Habit to build:** Every time you load a new dataset, run `.shape`, `.columns`, `.dtypes`, and `.head()` before doing anything else. It takes ten seconds and saves you from misunderstandings later.

### Exercise 2

Run `.shape`, `.dtypes`, and `.describe()` on your `un_members` DataFrame from Exercise 1. Based on the output of `.dtypes`, which columns are numeric and which are text? Answer in a comment.

In [9]:
# Your code here
df1.shape
df1.dtypes
df1.describe()

# the 'country' and 'continent' columns are text objects while the year_joined_un is an integer (numeric)

country           object
year_joined_un     int64
continent         object
dtype: object

---
## 3. Selecting Data

### Selecting columns

You can grab a single column with bracket notation. This returns a **Series** — pandas' term for a single column of data.

In [10]:
# Single column → returns a Series
df["country"]

0           Brazil
1          Germany
2            Japan
3          Nigeria
4    United States
Name: country, dtype: object

In [11]:
# Multiple columns → pass a list of column names → returns a DataFrame
df[["country", "gdp_trillions_usd"]]

         country  gdp_trillions_usd
0         Brazil               1.92
1        Germany               4.26
2          Japan               4.23
3        Nigeria               0.44
4  United States              25.46

Notice the double brackets `[[ ]]` when selecting multiple columns. The outer brackets are the pandas selection operator; the inner brackets define a Python list.

### Selecting rows

You can select rows by position (like list indexing) using `.iloc`, or by index label using `.loc`.

In [12]:
# .iloc uses integer positions (0-based), just like a Python list
df.iloc[0]       # first row

country                       Brazil
population_millions              214
gdp_trillions_usd               1.92
region                 South America
Name: 0, dtype: object

In [13]:
df.iloc[1:3]     # rows at positions 1 and 2 (the end is exclusive, like slicing)

   country  population_millions  gdp_trillions_usd  region
1  Germany                   84               4.26  Europe
2    Japan                  125               4.23    Asia

In [14]:
# .loc uses the index labels. Since our index is 0, 1, 2, ...
# it looks the same here, but .loc is inclusive on both ends.
df.loc[1:3]      # rows with index labels 1, 2, AND 3

   country  population_millions  gdp_trillions_usd  region
1  Germany                   84               4.26  Europe
2    Japan                  125               4.23    Asia
3  Nigeria                  223               0.44  Africa

The `.iloc` vs `.loc` distinction trips everyone up at first. The short version: use `.iloc` when you're thinking in terms of position ("give me the first three rows"), and `.loc` when you're thinking in terms of labels.

### Exercise 3

Using the `df` DataFrame:

a) Select just the `"country"` and `"region"` columns and display them.

b) Use `.iloc` to select the last two rows.

c) Run both `.loc[1:3]` and `.iloc[1:3]`. How many rows does each return? Explain the difference in a comment.

In [16]:
# 3a: Your code here
df[['country', 'region']]

         country         region
0         Brazil  South America
1        Germany         Europe
2          Japan           Asia
3        Nigeria         Africa
4  United States  North America

In [18]:
# 3b: Your code here
df.iloc[3:5]

         country  population_millions  gdp_trillions_usd         region
3        Nigeria                  223               0.44         Africa
4  United States                  333              25.46  North America

In [21]:
# 3c: Your code here — run both and explain the difference in a comment
df.loc[1:3]   # Includes three observations (index values 1-3)
df.iloc[1:3]  # Only includes the first two rows

   country  population_millions  gdp_trillions_usd  region
1  Germany                   84               4.26  Europe
2    Japan                  125               4.23    Asia

---
## 4. Filtering Rows

This is where pandas starts to feel powerful. You can filter a DataFrame by writing a condition, and pandas returns only the rows where that condition is `True`.

Let's say we want countries with GDP above $4 trillion.

In [22]:
# Step 1: The condition itself produces a Series of True/False values
df["gdp_trillions_usd"] > 4

0    False
1     True
2     True
3    False
4     True
Name: gdp_trillions_usd, dtype: bool

In [23]:
# Step 2: Pass that True/False series back into the DataFrame
# Pandas keeps only the rows where the value is True

high_gdp = df[df["gdp_trillions_usd"] > 4]
high_gdp

         country  population_millions  gdp_trillions_usd         region
1        Germany                   84               4.26         Europe
2          Japan                  125               4.23           Asia
4  United States                  333              25.46  North America

You can combine conditions with `&` (and) and `|` (or). Each condition needs its own parentheses.

In [24]:
# Countries with GDP > 4 trillion AND population > 100 million
df[(df["gdp_trillions_usd"] > 4) & (df["population_millions"] > 100)]

         country  population_millions  gdp_trillions_usd         region
2          Japan                  125               4.23           Asia
4  United States                  333              25.46  North America

### Exercise 4

Using the `df` DataFrame:

a) Filter for countries with a population over 200 million. How many are there?

b) Filter for countries that are in either `"Asia"` or `"Europe"`. (Hint: use `|` for "or".)

In [25]:
# 4a: Your code here
high_pop = df[df['population_millions'] > 200]
high_pop

         country  population_millions  gdp_trillions_usd         region
0         Brazil                  214               1.92  South America
3        Nigeria                  223               0.44         Africa
4  United States                  333              25.46  North America

In [26]:
# 4b: Your code here
df[(df['region'] == 'Asia') | (df['region'] == 'Europe')]

   country  population_millions  gdp_trillions_usd  region
1  Germany                   84               4.26  Europe
2    Japan                  125               4.23    Asia

---
## 5. Adding and Modifying Columns

You can create new columns from existing ones, just like adding a formula column in a spreadsheet.

In [27]:
# GDP per capita (in USD)
# GDP is in trillions, population is in millions,
# so (trillions / millions) = millions → multiply by 1e6 to get USD

df["gdp_per_capita"] = (df["gdp_trillions_usd"] / df["population_millions"]) * 1e6
df

,country,population_millions,gdp_trillions_usd,region,gdp_per_capita
0,Brazil,214,1.92,South America,8971.962617
1,Germany,84,4.26,Europe,50714.285714
2,Japan,125,4.23,Asia,33840.000000
3,Nigeria,223,0.44,Africa,1973.094170
4,United States,333,25.46,North America,76456.456456

Notice how the arithmetic operated on every row at once — no `for` loop needed. This is one of pandas' key advantages: **vectorized operations** let you work on entire columns in a single expression.

### Exercise 5

Add a new column to `df` called `"gdp_per_capita_thousands"` that expresses GDP per capita in thousands of USD (divide `gdp_per_capita` by 1000). Display the result.

In [28]:
# Your code here
df['gdp_per_capita_thousands'] = (df['gdp_per_capita'] / 1000)
df

,country,population_millions,gdp_trillions_usd,region,gdp_per_capita,gdp_per_capita_thousands
0,Brazil,214,1.92,South America,8971.962617,8.971963
1,Germany,84,4.26,Europe,50714.285714,50.714286
2,Japan,125,4.23,Asia,33840.000000,33.840000
3,Nigeria,223,0.44,Africa,1973.094170,1.973094
4,United States,333,25.46,North America,76456.456456,76.456456

---
## 6. Sorting

`.sort_values()` reorders rows. This is useful for ranking — which country has the highest GDP per capita?

In [29]:
df.sort_values("gdp_per_capita", ascending=False)

,country,population_millions,gdp_trillions_usd,region,gdp_per_capita,gdp_per_capita_thousands
4,United States,333,25.46,North America,76456.456456,76.456456
1,Germany,84,4.26,Europe,50714.285714,50.714286
2,Japan,125,4.23,Asia,33840.000000,33.840000
0,Brazil,214,1.92,South America,8971.962617,8.971963
3,Nigeria,223,0.44,Africa,1973.094170,1.973094

### Exercise 6

Sort `df` by `"population_millions"` in ascending order (smallest to largest). Which country has the smallest population in our dataset?

In [30]:
# Your code here
df.sort_values('population_millions', ascending = True) # Germany

,country,population_millions,gdp_trillions_usd,region,gdp_per_capita,gdp_per_capita_thousands
1,Germany,84,4.26,Europe,50714.285714,50.714286
2,Japan,125,4.23,Asia,33840.000000,33.840000
0,Brazil,214,1.92,South America,8971.962617,8.971963
3,Nigeria,223,0.44,Africa,1973.094170,1.973094
4,United States,333,25.46,North America,76456.456456,76.456456

---
## 7. Reading Data from Files and Panel Data

In practice, you'll almost never type data in by hand. Datasets come as CSV files, Excel spreadsheets, or other formats. Pandas makes loading them straightforward.

```python
# Reading a CSV file:
df = pd.read_csv("my_data.csv")

# Reading an Excel file:
df = pd.read_excel("my_data.xlsx")
```

Both return a DataFrame, ready to work with. We'll use `pd.read_excel()` in Part II to load a real dataset.

For now, let's build a slightly larger dataset by hand that mimics the kind of **panel data** you'll see in Part II — multiple countries observed across multiple years.

In [31]:
# A small panel dataset: inflation rates for 3 countries over 4 years

panel_data = {
    "country": ["Argentina"] * 4 + ["Germany"] * 4 + ["Kenya"] * 4,
    "year": [2019, 2020, 2021, 2022] * 3,
    "inflation_pct": [
        53.5, 42.0, 48.4, 72.4,     # Argentina
        1.4,  0.4,  3.2,  8.7,      # Germany
        5.2,  5.4,  6.1,  7.6       # Kenya
    ]
}

panel = pd.DataFrame(panel_data)
panel

      country  year  inflation_pct
0   Argentina  2019           53.5
1   Argentina  2020           42.0
2   Argentina  2021           48.4
3   Argentina  2022           72.4
4     Germany  2019            1.4
5     Germany  2020            0.4
6     Germany  2021            3.2
7     Germany  2022            8.7
8       Kenya  2019            5.2
9       Kenya  2020            5.4
10      Kenya  2021            6.1
11      Kenya  2022            7.6

This structure — one row per country-year, with each variable in its own column — is called **panel data** or **long format**. It's extremely common in economics and political science. The Part II dataset follows this same pattern, just with more countries and more variables.

### Exercise 7

Add a fourth country to the panel. Create a new DataFrame called `panel_expanded` that includes all the original data plus 4 rows for a country of your choice (same years: 2019–2022) with inflation rates you make up. Display the full DataFrame.

Hint: Build a small DataFrame for just the new country, then use `pd.concat([panel, new_df], ignore_index=True)` to stack them together.

In [34]:
# Your code here
new_df = {
    "country": ['Guatemala'] * 4,
    "year": [2019,2020,2021,2022],
    "inflation_pct": [9.8, 7.2, 6.6, 8.0]
}

new_df = pd.DataFrame(new_df)


pd.concat([panel, new_df], ignore_index=True)

      country  year  inflation_pct
0   Argentina  2019           53.5
1   Argentina  2020           42.0
2   Argentina  2021           48.4
3   Argentina  2022           72.4
4     Germany  2019            1.4
5     Germany  2020            0.4
6     Germany  2021            3.2
7     Germany  2022            8.7
8       Kenya  2019            5.2
9       Kenya  2020            5.4
10      Kenya  2021            6.1
11      Kenya  2022            7.6
12  Guatemala  2019            9.8
13  Guatemala  2020            7.2
14  Guatemala  2021            6.6
15  Guatemala  2022            8.0

---
## 8. Renaming Columns

Real-world datasets often have ugly column names — long, inconsistent, full of spaces. Renaming them makes your code much easier to read and write.

In [35]:
# Imagine a dataset where a column is named something unwieldy:
ugly = panel.rename(columns={"inflation_pct": "Inflation, Annual percentages of average consumer prices"})
ugly.columns

Index(['country', 'year',
       'Inflation, Annual percentages of average consumer prices'],
      dtype='object')

In [36]:
# .rename() lets you fix it. Pass a dictionary: {old_name: new_name}
clean = ugly.rename(columns={
    "Inflation, Annual percentages of average consumer prices": "inflation"
})
clean.columns

Index(['country', 'year', 'inflation'], dtype='object')

You'll use this in Part II — the real dataset has column names that are full sentences.

### Exercise 8

The DataFrame below has two columns with clunky names. Rename them to something shorter and more usable, then display `.columns` to confirm it worked.

In [38]:
trade_data = pd.DataFrame({
    "Country or Area Name (as reported by source)": ["Mexico", "Canada", "Vietnam"],
    "Total Bilateral Trade Volume in Millions of USD (2023)": [798000, 718000, 139000]
})

# Rename the columns to something manageable, then display .columns
# Your code here
trade_data_clean = trade_data.rename(columns = {"Country or Area Name (as reported by source)": 'Country', 'Total Bilateral Trade Volume in Millions of USD (2023)':'Trade_Volume'
                                               })
trade_data_clean.columns

Index(['Country', 'Trade_Volume'], dtype='object')

---
## 9. Handling Messy Data

Real data is messy. Numbers get stored as text, cells are empty, rows contain junk. Pandas gives you tools to deal with this.

### Converting types with `pd.to_numeric()`

In [39]:
# Sometimes numbers arrive as strings (this is common with Excel data)
messy = pd.DataFrame({
    "country": ["Chile", "Egypt", "Poland", "Somalia"],
    "inflation": ["4.5", "13.9", "N/A", "6.1"]   # note: these are strings, not numbers
})

messy.dtypes

country      object
inflation    object
dtype: object

In [40]:
# pd.to_numeric() converts a column to numbers.
# errors='coerce' turns anything it can't convert (like "N/A") into NaN
# (NaN = "Not a Number" — pandas' way of representing missing data)

messy["inflation"] = pd.to_numeric(messy["inflation"], errors="coerce")
messy

   country  inflation
0    Chile        4.5
1    Egypt       13.9
2   Poland        NaN
3  Somalia        6.1

In [41]:
# Now the dtype is float64 — a real number
messy.dtypes

country       object
inflation    float64
dtype: object

### Checking for missing values

In [42]:
# .isna() returns True where data is missing
messy["inflation"].isna()

0    False
1    False
2     True
3    False
Name: inflation, dtype: bool

In [43]:
# .notna() is the opposite — True where data exists
# This is handy for filtering out missing values
messy[messy["inflation"].notna()]

   country  inflation
0    Chile        4.5
1    Egypt       13.9
3  Somalia        6.1

### Exercise 9

The DataFrame below has a `"gdp"` column where the data arrived messy — some entries are numbers, some are text, and some are missing. Convert `"gdp"` to numeric, then filter the DataFrame to show only rows where GDP data exists (is not NaN).

In [44]:
messy_gdp = pd.DataFrame({
    "country": ["France", "India", "Peru", "Thailand", "Zambia"],
    "gdp": ["2.78", "3.39", "not reported", "0.50", ".."]
})

# Step 1: Convert the "gdp" column to numeric (coerce errors)
# Step 2: Filter to keep only rows where gdp is not NaN
# Your code here

messy_gdp["gdp"] = pd.to_numeric(messy_gdp["gdp"], errors="coerce")

messy_gdp[messy_gdp['gdp'].notna()]

    country   gdp
0    France  2.78
1     India  3.39
3  Thailand  0.50

---
## 10. Using `.apply()` and Lambda Functions

Sometimes you need to apply a custom operation to every value in a column. The `.apply()` method does exactly this — it runs a function on each element (or each row) and returns the results.

A **lambda function** is just a small, anonymous function you can write inline instead of defining with `def`.

In [45]:
# Quick refresher on lambda:
# A regular function:
def double(x):
    return x * 2

# The same thing as a lambda:
double_lambda = lambda x: x * 2

print(double(5))         # 10
print(double_lambda(5))  # 10

10
10

In [46]:
# Using .apply() with a lambda on our panel data
# Let's classify each inflation observation as "high" or "normal"

panel["category"] = panel["inflation_pct"].apply(lambda x: "high" if x > 10 else "normal")
panel

      country  year  inflation_pct category
0   Argentina  2019           53.5     high
1   Argentina  2020           42.0     high
2   Argentina  2021           48.4     high
3   Argentina  2022           72.4     high
4     Germany  2019            1.4   normal
5     Germany  2020            0.4   normal
6     Germany  2021            3.2   normal
7     Germany  2022            8.7   normal
8       Kenya  2019            5.2   normal
9       Kenya  2020            5.4   normal
10      Kenya  2021            6.1   normal
11      Kenya  2022            7.6   normal

You can also use `.apply()` to filter. Instead of the vectorized comparison we saw earlier (`df[df["col"] > value]`), you can write:

```python
df[df["col"].apply(lambda x: x > value)]
```

Both produce the same result. The lambda version is more flexible — you can put any logic you want inside it — but the vectorized version is faster on large datasets. Part II asks you to practice with lambda, so you'll use `.apply()` there.

In [47]:
# Filtering with lambda: same result as panel[panel["inflation_pct"] > 10]
panel[panel["inflation_pct"].apply(lambda x: x > 10)]

     country  year  inflation_pct category
0  Argentina  2019           53.5     high
1  Argentina  2020           42.0     high
2  Argentina  2021           48.4     high
3  Argentina  2022           72.4     high

### Exercise 10

Using the `panel` DataFrame and `.apply()` with a lambda:

a) Create a new column called `"severity"` that labels each row as `"crisis"` if inflation is above 40, `"elevated"` if between 5 and 40 (inclusive), and `"stable"` otherwise.

b) Filter the panel to show only the `"crisis"` rows. Which country and years appear?

In [50]:
# 10a: Your code here
panel["severity"] = panel["inflation_pct"].apply(lambda x: "crisis" if x > 40 else ("elevated" if 5 < x <= 40 else "stable")
)
panel

      country  year  inflation_pct category  severity
0   Argentina  2019           53.5     high    crisis
1   Argentina  2020           42.0     high    crisis
2   Argentina  2021           48.4     high    crisis
3   Argentina  2022           72.4     high    crisis
4     Germany  2019            1.4   normal    stable
5     Germany  2020            0.4   normal    stable
6     Germany  2021            3.2   normal    stable
7     Germany  2022            8.7   normal  elevated
8       Kenya  2019            5.2   normal  elevated
9       Kenya  2020            5.4   normal  elevated
10      Kenya  2021            6.1   normal  elevated
11      Kenya  2022            7.6   normal  elevated

In [51]:
# 10b: Your code here
panel[panel["severity"].apply(lambda x: x == 'crisis')]

     country  year  inflation_pct category severity
0  Argentina  2019           53.5     high   crisis
1  Argentina  2020           42.0     high   crisis
2  Argentina  2021           48.4     high   crisis
3  Argentina  2022           72.4     high   crisis

---
## 11. Grouping and Aggregating

One of the most common operations in data analysis is splitting your data into groups, computing something for each group, and combining the results. Pandas calls this **groupby**.

Example: What's the average inflation rate for each country across all years?

In [52]:
panel.groupby("country")["inflation_pct"].mean()

country
Argentina    54.075
Germany       3.425
Kenya         6.075
Name: inflation_pct, dtype: float64

That one line does a lot:
1. **Groups** the rows by country
2. **Selects** the inflation column within each group
3. **Computes** the mean for each group

You can chain `.sort_values()` to rank the results, and `.head(n)` to get the top N.

In [53]:
# Top 2 countries by average inflation
panel.groupby("country")["inflation_pct"].mean().sort_values(ascending=False).head(2)

country
Argentina    54.075
Kenya         6.075
Name: inflation_pct, dtype: float64

### Turning a grouped result back into a DataFrame

The result of `.groupby().mean()` is a **Series** (one column, indexed by the group). If you want it as a proper DataFrame with columns, use `.reset_index()`.

In [54]:
avg_inflation = panel.groupby("country")["inflation_pct"].mean().sort_values(ascending=False)

# Before reset_index — it's a Series with 'country' as the index
print(type(avg_inflation))
print(avg_inflation)
print()

<class 'pandas.core.series.Series'>
country
Argentina    54.075
Kenya         6.075
Germany       3.425
Name: inflation_pct, dtype: float64

In [55]:
# After reset_index — it's a DataFrame with 'country' as a regular column
avg_inflation_df = avg_inflation.reset_index()
print(type(avg_inflation_df))
avg_inflation_df

<class 'pandas.core.frame.DataFrame'>

     country  inflation_pct
0  Argentina         54.075
1      Kenya          6.075
2    Germany          3.425

### Exercise 11

Using the `panel` DataFrame:

a) Find the **maximum** inflation rate for each country (use `.max()` instead of `.mean()`).

b) Sort the result in descending order and convert it to a DataFrame using `.reset_index()`. Round the values to 1 decimal place using `.round(1)`.

In [58]:
# Your code here
panel.groupby("country")["inflation_pct"].max()

max_inflation = panel.groupby("country")["inflation_pct"].max().sort_values(ascending=False)
max_inflation_df = max_inflation.reset_index()

max_inflation_df

     country  inflation_pct
0  Argentina           72.4
1    Germany            8.7
2      Kenya            7.6

---
## 12. Counting Unique Values

How many distinct countries are in the dataset? How many distinct years?

In [59]:
# .unique() returns an array of distinct values
print(panel["country"].unique())

# len() counts them
print(f"Number of countries: {len(panel['country'].unique())}")

['Argentina' 'Germany' 'Kenya']
Number of countries: 3

In [60]:
# .nunique() is a shortcut — it gives you the count directly
panel["year"].nunique()

4

### Exercise 12

Using the `panel` DataFrame: first, filter for rows where inflation is above 5%. Then, from that filtered result, answer: how many *unique countries* experienced inflation above 5%? How many *unique years* had at least one country above 5%?

In [61]:
# Your code here
panel[panel["inflation_pct"].apply(lambda x: x > 5)].nunique()

country          3
year             4
inflation_pct    9
category         2
severity         2
dtype: int64

---
## 13. Merging DataFrames

Sometimes the data you need lives in two separate tables and you need to join them. Pandas' `pd.merge()` works like a database join or an Excel VLOOKUP.

In [62]:
# Suppose we have a separate table of crisis indicators
crisis_data = pd.DataFrame({
    "country": ["Argentina", "Argentina", "Germany"],
    "year": [2020, 2022, 2022],
    "crisis_type": ["currency", "currency", "energy"]
})

crisis_data

     country  year crisis_type
0  Argentina  2020    currency
1  Argentina  2022    currency
2    Germany  2022      energy

In [63]:
# Merge on shared columns (country AND year)
# how="left" keeps all rows from the left DataFrame,
# filling NaN where there's no match in the right DataFrame.

merged = pd.merge(panel, crisis_data, on=["country", "year"], how="left")
merged

      country  year  inflation_pct category  severity crisis_type
0   Argentina  2019           53.5     high    crisis         NaN
1   Argentina  2020           42.0     high    crisis    currency
2   Argentina  2021           48.4     high    crisis         NaN
3   Argentina  2022           72.4     high    crisis    currency
4     Germany  2019            1.4   normal    stable         NaN
5     Germany  2020            0.4   normal    stable         NaN
6     Germany  2021            3.2   normal    stable         NaN
7     Germany  2022            8.7   normal  elevated      energy
8       Kenya  2019            5.2   normal  elevated         NaN
9       Kenya  2020            5.4   normal  elevated         NaN
10      Kenya  2021            6.1   normal  elevated         NaN
11      Kenya  2022            7.6   normal  elevated         NaN

The NaN values in `crisis_type` mean "no crisis recorded for that country-year." You could now filter for rows where a crisis occurred using `.notna()`.

In [64]:
merged[merged["crisis_type"].notna()]

     country  year  inflation_pct category  severity crisis_type
1  Argentina  2020           42.0     high    crisis    currency
3  Argentina  2022           72.4     high    crisis    currency
7    Germany  2022            8.7   normal  elevated      energy

### Exercise 13

Below is a small DataFrame of election years. Merge it onto the `panel` DataFrame using a left join on `"country"` and `"year"`. Then filter the merged result to show only rows where an election took place. What was the inflation rate in each of those election years?

In [65]:
elections = pd.DataFrame({
    "country": ["Argentina", "Kenya", "Germany"],
    "year": [2019, 2022, 2021],
    "election_type": ["presidential", "presidential", "parliamentary"]
})

# Merge elections onto panel, then filter for rows where an election occurred
# Your code here
merged_election = pd.merge(panel, elections, on=["country", "year"], how="left")
merged_election[merged_election["election_type"].notna()]

      country  year  inflation_pct category  severity  election_type
0   Argentina  2019           53.5     high    crisis   presidential
6     Germany  2021            3.2   normal    stable  parliamentary
11      Kenya  2022            7.6   normal  elevated   presidential

---
## 14. Formatting Output with `.apply()` and Lambda

When you're presenting results, raw floats aren't always readable. You can use `.apply()` with a lambda to format numbers as strings.

In [66]:
# Round and format inflation as a percentage string
panel["inflation_display"] = panel["inflation_pct"].apply(lambda x: f"{x:,.1f}%")
panel[["country", "year", "inflation_display"]]

      country  year inflation_display
0   Argentina  2019             53.5%
1   Argentina  2020             42.0%
2   Argentina  2021             48.4%
3   Argentina  2022             72.4%
4     Germany  2019              1.4%
5     Germany  2020              0.4%
6     Germany  2021              3.2%
7     Germany  2022              8.7%
8       Kenya  2019              5.2%
9       Kenya  2020              5.4%
10      Kenya  2021              6.1%
11      Kenya  2022              7.6%

### Exercise 14

Using the `df` DataFrame (our original 5-country dataset), create a new column called `"gdp_display"` that formats `"gdp_trillions_usd"` as a dollar string — for example, `"$4.26T"`. Use `.apply()` with a lambda. Display just the `"country"` and `"gdp_display"` columns.

In [72]:
# Your code here
df['gdp_display'] = df['gdp_trillions_usd'].apply(lambda x: f"${x:,.2f}T")

df[['country', 'gdp_display']]

         country gdp_display
0         Brazil      $1.92T
1        Germany      $4.26T
2          Japan      $4.23T
3        Nigeria      $0.44T
4  United States     $25.46T

---
## 15. Using `.filter()` to Select Columns

If you only want certain columns and don't want to type all the bracket notation, `.filter()` is a convenient shorthand.

In [73]:
# Equivalent to panel[["country", "year", "inflation_pct"]]
panel.filter(["country", "year", "inflation_pct"])

      country  year  inflation_pct
0   Argentina  2019           53.5
1   Argentina  2020           42.0
2   Argentina  2021           48.4
3   Argentina  2022           72.4
4     Germany  2019            1.4
5     Germany  2020            0.4
6     Germany  2021            3.2
7     Germany  2022            8.7
8       Kenya  2019            5.2
9       Kenya  2020            5.4
10      Kenya  2021            6.1
11      Kenya  2022            7.6

---
## Putting It All Together

Let's walk through a mini-analysis that chains several of these operations — the same pattern you'll follow in Part II.

**Question:** Which countries experienced inflation above 30%, and what was their average rate in those high-inflation years?

In [74]:
# Start from the panel DataFrame
# Step 1: Filter for inflation above 30%
high_infl = panel[panel["inflation_pct"].apply(lambda x: x > 30)]

# Step 2: How many countries?
print(f"Countries with >30% inflation: {len(high_infl['country'].unique())}")

# Step 3: Average inflation in those episodes
avg_by_country = high_infl.groupby("country")["inflation_pct"].mean().reset_index()
avg_by_country["inflation_pct"] = avg_by_country["inflation_pct"].apply(lambda x: round(x, 2))
avg_by_country

Countries with >30% inflation: 1

     country  inflation_pct
0  Argentina          54.08

### Exercise 15 (Challenge)

This one combines everything. Using the `panel` DataFrame:

1. Rename `"inflation_pct"` to `"inflation"`
2. Filter for inflation above 6% using `.apply()` with a lambda
3. Select only the `"country"`, `"year"`, and `"inflation"` columns using `.filter()`
4. Round the inflation values to 1 decimal place using `.apply()` with a lambda
5. Find the top 2 countries by average inflation (using `.groupby()`, `.mean()`, `.sort_values()`, `.head()`)
6. Convert the result to a DataFrame with `.reset_index()`

In [90]:
# Your code here — try to do it step by step, one operation at a time.
# You can use multiple cells if you want to check your work as you go.
panel = panel.rename(columns = {'inflation_pct':'inflation'
                         })
panel["inflation"] = pd.to_numeric(panel["inflation"], errors="coerce")

panel.filter(['country', 'year', 'inflation'])

panel['inflation'] = panel['inflation'].apply(lambda x: f" {x:,.1f}")

In [93]:

panel['inflation'] = pd.to_numeric(panel['inflation'], errors='coerce')


avg_inflation = panel.groupby("country")["inflation"].mean().sort_values(ascending=False).head(2)

avg_inflation_df = avg_inflation.reset_index()

avg_inflation_df

     country  inflation
0  Argentina     54.075
1      Kenya      6.075

---

## Quick Reference

| What you want to do | Code |
|---|---|
| Load a CSV | `pd.read_csv("file.csv")` |
| Load an Excel file | `pd.read_excel("file.xlsx")` |
| See dimensions | `df.shape` |
| See column names | `df.columns` |
| See data types | `df.dtypes` |
| First N rows | `df.head(n)` |
| Summary stats | `df.describe()` |
| Select one column | `df["col"]` |
| Select multiple columns | `df[["col1", "col2"]]` |
| Filter rows | `df[df["col"] > value]` |
| Filter with lambda | `df[df["col"].apply(lambda x: x > value)]` |
| Rename columns | `df.rename(columns={"old": "new"})` |
| Sort | `df.sort_values("col", ascending=False)` |
| Group and aggregate | `df.groupby("col")["val"].mean()` |
| Count unique values | `len(df["col"].unique())` or `df["col"].nunique()` |
| Convert to numeric | `pd.to_numeric(df["col"], errors="coerce")` |
| Check for missing data | `df["col"].isna()` / `df["col"].notna()` |
| Merge two DataFrames | `pd.merge(df1, df2, on="col")` |
| Series to DataFrame | `series.reset_index()` |

---
---
# Part II: Global Financial Crises Dataset

Below is a link to data collected over many years by Carmen Reinhart (with her coauthors Ken Rogoff, Christoph Trebesch, and Vincent Reinhart). These include Banking Crisis dates for more than 70 countries from 1800-present, exchange rate crises, stock market crises, sovereign debt growth and default, and many other data series.
Please download here:

https://www.hbs.edu/behavioral-finance-and-financial-stability/data/Pages/global.aspx

For the following, please show me that you know how to use lambda and map functions where possible and efficient.

Q1: Read the data from the excel file into a pandas data frame:

In [96]:
# Your code here
crisis = pd.read_excel('/Users/chriskalman/Downloads/20160923_global_crisis_data.xlsx')

Q2. From the dataset, create a new dataframe. Using a lambda function, select only those incidents where the annual inflation rate was 25% or higher. The dataframe should have three columns, Country Name, Year and Inflation rate.

In [101]:
crisis.head(3)

,Case,CC3,Country,Year,Banking Crisis,Banking_Crisis_Notes,Systemic Crisis,Gold Standard,exch_usd,exch_usd_alt1,...,Domestic_Debt_ Notes/Sources,"SOVEREIGN EXTERNAL DEBT 1: DEFAULT and RESTRUCTURINGS, 1800-2012--Does not include defaults on WWI debt to United States and United Kingdom and post-1975 defaults on Official External Creditors","SOVEREIGN EXTERNAL DEBT 2: DEFAULT and RESTRUCTURINGS, 1800-2012--Does not include defaults on WWI debt to United States and United Kingdom but includes post-1975 defaults on Official External Creditors",Defaults_External_Notes,GDP_Weighted_default,<,inflation,Independence,Currency Crises,Inflation Crises
0,NaN,NaN,NaN,NaN,x,NaN,x,x,NaN,NaN,...,NaN,x,NaN,NaN,x,x,NaN,x,x,x
1,1.0,DZA,Algeria,1800.0,0,NaN,0,0,NaN,NaN,...,NaN,0,0.0,NaN,0,NaN,NaN,0,0,0
2,1.0,DZA,Algeria,1801.0,0,NaN,0,0,NaN,NaN,...,NaN,0,0.0,NaN,0,NaN,NaN,0,0,0

In [102]:
# Your code here
crisis = crisis.rename(columns = {'Inflation, Annual percentages of average consumer prices': 'inflation'})

crisis['inflation'] = pd.to_numeric(crisis['inflation'], errors='coerce')

df1 = crisis[crisis['Country'], crisis['Year'], crisis['inflation'].apply(lambda x:x>25)]
df1

InvalidIndexError: (0             NaN
1         Algeria
2         Algeria
3         Algeria
4         Algeria
           ...
15186    Zimbabwe
15187    Zimbabwe
15188    Zimbabwe
15189    Zimbabwe
15190    Zimbabwe
Name: Country, Length: 15191, dtype: object, 0           NaN
1        1800.0
2        1801.0
3        1802.0
4        1803.0
          ...
15186    2012.0
15187    2013.0
15188    2014.0
15189    2015.0
15190    2016.0
Name: Year, Length: 15191, dtype: float64, 0        False
1        False
2        False
3        False
4        False
         ...
15186    False
15187    False
15188    False
15189    False
15190    False
Name: inflation, Length: 15191, dtype: bool)

In [119]:
df1 = crisis[crisis['inflation'] > 25][['Country', 'Year', 'inflation', 'Systemic Crisis']]
df1

        Country    Year     inflation Systemic Crisis
78      Algeria  1877.0  2.911605e+01               0
143     Algeria  1942.0  2.812500e+01               0
144     Algeria  1943.0  4.634146e+01               0
145     Algeria  1944.0  4.166667e+01               0
146     Algeria  1945.0  2.941176e+01               0
...         ...     ...           ...             ...
15178  Zimbabwe  2004.0  1.327468e+02               1
15179  Zimbabwe  2005.0  5.858444e+02               1
15180  Zimbabwe  2006.0  1.281114e+03               1
15181  Zimbabwe  2007.0  6.627989e+04               1
15182  Zimbabwe  2008.0  2.198970e+07               1

[839 rows x 4 columns]

Q3. Write code to tell me how many countries experienced 25% inflation or higher?

In [111]:
# Your code here

print(f"Number of countries:{len(df1['Country'].unique())}")

Number of countries:61

Q4. How many years across all countries were there events of 25% or higher inflation?

In [112]:
# Your code here
print(f"Number of years:{len(df1['Year'].unique())}")

Number of years:175

Q5. Of the years where inflation was 25% or higher, how many of those years resulted in a systemic crisis?

In [120]:
# Your code here
print(f"Number of years with +25% inflation and a concurrent systemic crisis: {len(df1[df1['Systemic Crisis'] == 1])}")

Number of years with +25% inflation and a concurrent systemic crisis: 109

Q6. What were the countries and years associated with the total from Q5?

In [125]:
# Your code here
df1[df1['Systemic Crisis'].apply(lambda x: x==1)]

         Country    Year     inflation Systemic Crisis
192      Algeria  1991.0  2.590000e+01               1
193      Algeria  1992.0  3.170000e+01               1
525    Argentina  1890.0  4.094650e+01               1
615    Argentina  1980.0  1.007640e+02               1
616    Argentina  1981.0  1.044770e+02               1
...          ...     ...           ...             ...
15178   Zimbabwe  2004.0  1.327468e+02               1
15179   Zimbabwe  2005.0  5.858444e+02               1
15180   Zimbabwe  2006.0  1.281114e+03               1
15181   Zimbabwe  2007.0  6.627989e+04               1
15182   Zimbabwe  2008.0  2.198970e+07               1

[109 rows x 4 columns]

Q7. At times of civil unrest or war, what was the average interest rate?

In [128]:
df = crisis

In [129]:
# Your code here
import numpy as np


# --- Convert key columns to numeric ---
df['Year'] = pd.to_numeric(df['Year'], errors='coerce')
df['Independence'] = pd.to_numeric(df['Independence'], errors='coerce')
df['inflation'] = pd.to_numeric(df['inflation'], errors='coerce')

# --- Drop the header/legend row (row 0 with NaN Case) ---
df = df.dropna(subset=['Case'])

# --- Find the first year each country gained independence ---
independence_years = (
    df[df['Independence'] == 1]
    .groupby('Country')['Year']
    .min()
    .reset_index()
    .rename(columns={'Year': 'independence_year'})
)

# --- Filter out countries that always had or never received independence ---
# "Always had" = Independence == 1 for ALL their rows
# "Never received" = Independence == 1 for NONE of their rows

country_independence_counts = df.groupby('Country')['Independence'].sum()
total_rows_per_country = df.groupby('Country')['Year'].count()

always_independent = country_independence_counts[
    country_independence_counts == total_rows_per_country
].index

never_independent = country_independence_counts[
    country_independence_counts == 0
].index

countries_to_exclude = set(always_independent).union(set(never_independent))

independence_years = independence_years[
    ~independence_years['Country'].isin(countries_to_exclude)
]

print(f"Countries included in analysis: {len(independence_years)}")
print(f"Countries excluded (always independent): {len(always_independent)}")
print(f"Countries excluded (never independent): {len(never_independent)}")

# --- Merge independence year back onto the main dataframe ---
df_merged = df.merge(independence_years, on='Country', how='inner')

# --- Calculate years relative to independence ---
df_merged['years_from_independence'] = df_merged['Year'] - df_merged['independence_year']

# --- Filter to the 3-year window before and after independence ---
# Before: -3 to -1 | After: 1 to 3 (year 0 = independence year itself)
before = df_merged[df_merged['years_from_independence'].between(-3, -1)].copy()
after  = df_merged[df_merged['years_from_independence'].between(1, 3)].copy()

# --- Compute average inflation per country in each window ---
avg_before = (
    before.groupby('Country')['inflation']
    .mean()
    .reset_index()
    .rename(columns={'inflation': 'avg_inflation_before'})
)

avg_after = (
    after.groupby('Country')['inflation']
    .mean()
    .reset_index()
    .rename(columns={'inflation': 'avg_inflation_after'})
)

# --- Combine results ---
results = avg_before.merge(avg_after, on='Country', how='outer')
results = results.merge(independence_years, on='Country', how='left')
results = results.sort_values('Country').reset_index(drop=True)

# --- Overall averages across all qualifying countries ---
overall_avg_before = results['avg_inflation_before'].mean()
overall_avg_after  = results['avg_inflation_after'].mean()

print("\n--- Per-Country Inflation Averages Around Independence ---")
print(results[['Country', 'independence_year', 'avg_inflation_before', 'avg_inflation_after']].to_string(index=False))

print(f"\n--- Overall Average Inflation (3 Years BEFORE Independence): {overall_avg_before:.2f}%")
print(f"--- Overall Average Inflation (3 Years AFTER  Independence): {overall_avg_after:.2f}%")
print(f"--- Change in Average Inflation (After - Before): {overall_avg_after - overall_avg_before:.2f}%")

Countries included in analysis: 52
Countries excluded (always independent): 18
Countries excluded (never independent): 0

--- Per-Country Inflation Averages Around Independence ---
                 Country  independence_year  avg_inflation_before  avg_inflation_after
                 Algeria             1962.0              5.849340                  NaN
                  Angola             1975.0             19.629462            66.056775
               Argentina             1816.0             16.666667             2.020202
               Australia             1901.0             -0.442779            -1.369094
                 Belgium             1830.0             19.829380            20.014312
                 Bolivia             1825.0                   NaN                  NaN
                  Brazil             1822.0             -8.017846                  NaN
                  Canada             1867.0                   NaN            -0.163206
Central African Republic             1960.0              7.785908             5.987990
                   Chile             1818.0              6.721026            -0.081313
                Colombia             1819.0                   NaN                  NaN
              Costa Rica             1839.0                   NaN                  NaN
            CoteD'Ivoire             1960.0             13.515482             7.657437
      Dominican Republic             1844.0                   NaN                  NaN
                 Ecuador             1830.0                   NaN                  NaN
                   Egypt             1831.0                   NaN                  NaN
             El Salvador             1838.0                   NaN                  NaN
                 Finland             1917.0             17.810847            76.876959
                   Ghana             1957.0              2.220145             3.026182
                  Greece             1829.0                   NaN                  NaN
               Guatemala             1838.0                   NaN                  NaN
                Honduras             1838.0                   NaN                  NaN
                 Hungary             1918.0                   NaN                  NaN
                 Iceland             1918.0             31.573523             4.812462
                   India             1947.0              2.187530             3.209733
               Indonesia             1945.0             28.619401            48.189073
                   Kenya             1963.0              2.035603             3.079509
                   Korea             1945.0                   NaN                  NaN
                Malaysia             1963.0             -0.178387            -0.028854
               Mauritius             1963.0              0.685056             2.234108
                  Mexico             1821.0                   NaN                  NaN
                 Morocco             1956.0              2.375784             1.510018
                 Myanmar             1948.0              1.900585             5.854664
             New Zealand             1919.0              8.865558             0.003156
               Nicaragua             1838.0                   NaN                  NaN
                 Nigeria             1960.0              0.951335             2.700166
                  Norway             1905.0             -1.609789             2.617630
                  Panama             1903.0                   NaN                  NaN
                Paraguay             1818.0                   NaN                  NaN
                    Peru             1821.0              3.005404            -2.181636
             Philippines             1946.0            141.732283           -11.450459
                  Poland             1918.0                   NaN                  NaN
                 Romania             1878.0                   NaN                  NaN
               Singapore             1965.0              1.831830             1.616561
            South Africa             1910.0              0.563945             2.604489
               Sri Lanka             1948.0              7.346060             2.967866
                  Taiwan             1945.0                   NaN                  NaN
                 Tunisia             1956.0              1.198906             0.819190
                 Uruguay             1810.0                   NaN                  NaN
               Venezuela             1829.0                   NaN             1.415094
                  Zambia             1964.0              0.355650             7.806026
                Zimbabwe             1965.0              1.887929             2.291151

--- Overall Average Inflation (3 Years BEFORE Independence): 11.23%
--- Overall Average Inflation (3 Years AFTER  Independence): 8.67%
--- Change in Average Inflation (After - Before): -2.56%

In [130]:
import pandas as pd
import numpy as np

# --- Rename the inflation column for easier handling ---
df = df.rename(columns={'Inflation, Annual percentages of average consumer prices': 'inflation'})

# --- Convert key columns to numeric ---
df['Year'] = pd.to_numeric(df['Year'], errors='coerce')
df['Independence'] = pd.to_numeric(df['Independence'], errors='coerce')
df['inflation'] = pd.to_numeric(df['inflation'], errors='coerce')

# --- Drop the header/legend row (row 0 with NaN Case) ---
df = df.dropna(subset=['Case'])

# --- Find the first year each country gained independence ---
independence_years = (
    df[df['Independence'] == 1]
    .groupby('Country')['Year']
    .min()
    .reset_index()
    .rename(columns={'Year': 'independence_year'})
)

# --- Filter out countries that always had or never received independence ---
country_independence_counts = df.groupby('Country')['Independence'].sum()
total_rows_per_country = df.groupby('Country')['Year'].count()

always_independent = country_independence_counts[
    country_independence_counts == total_rows_per_country
].index

never_independent = country_independence_counts[
    country_independence_counts == 0
].index

countries_to_exclude = set(always_independent).union(set(never_independent))

independence_years = independence_years[
    ~independence_years['Country'].isin(countries_to_exclude)
]

# --- Merge independence year back onto the main dataframe ---
df_merged = df.merge(independence_years, on='Country', how='inner')

# --- Calculate years relative to independence ---
df_merged['years_from_independence'] = df_merged['Year'] - df_merged['independence_year']

# --- Filter to the full 6-year window (3 before + 3 after, excluding year 0) ---
window = df_merged[
    (df_merged['years_from_independence'].between(-3, -1)) |
    (df_merged['years_from_independence'].between(1, 3))
].copy()

# --- Single average inflation rate across ALL 6 years for ALL qualifying countries ---
overall_avg_inflation = window['inflation'].mean()

print(f"Average Inflation Rate Across All 6 Years Around Independence: {overall_avg_inflation:.2f}%")

Average Inflation Rate Across All 6 Years Around Independence: 8.68%

Q8: Create a new dataframe that lists the top five countries with the average highest interest rates historically, with a column for the country, and the average rate.

In [131]:
# Your code here
df['inflation'] = pd.to_numeric(df['inflation'], errors='coerce')

top5 = (
    df.groupby('Country')['inflation']
    .mean()
    .reset_index()
    .rename(columns={'inflation': 'avg_inflation_rate'})
    .sort_values('avg_inflation_rate', ascending=False)
    .head(5)
    .reset_index(drop=True)
)

print(top5)

     Country  avg_inflation_rate
0    Hungary        1.035976e+25
1     Greece        1.650901e+08
2    Germany        1.023972e+08
3   Zimbabwe        2.371989e+05
4  Nicaragua        3.920163e+02

Q9: Create a new dataframe that lists the countries and years where there was "negative inflation".
What does negative inflation mean, and why did it occur?

In [133]:
# Your code here
df2 = crisis[crisis['inflation'] < 0][['Country', 'Year', 'inflation']]
df2
# Negative inflation means that the currency of that country actually strengthened over the course of the year relative to its value at 
# the beginning of the year. Strong economic performance like this could be caused by changes in trade, payoff of internal investment,
# increase in stability, etc.

        Country    Year  inflation
73      Algeria  1872.0  -3.718593
75      Algeria  1874.0  -3.848561
76      Algeria  1875.0 -20.924178
77      Algeria  1876.0  -1.769547
79      Algeria  1878.0  -1.492537
...         ...     ...        ...
15112  Zimbabwe  1938.0  -2.912621
15183  Zimbabwe  2009.0  -7.670000
15188  Zimbabwe  2014.0  -0.213000
15189  Zimbabwe  2015.0  -2.399000
15190  Zimbabwe  2016.0  -1.239000

[2301 rows x 3 columns]

Your explanation here: